### PR TITLE
chore(demo): misaligned column fix

### LINKED ISSUE #2568: 🐞 - `tui-doc-documentation` Column header misaligned with the rest of the column cells
### Which @taiga-ui/* package(s) are the source of the bug?

addon-doc

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/services/scroll-service/API

### Is this issue blocking you?

Non-Blocking

### Description

When `showValues` is set to `false`, last column header is misaligned with the rest of column cells.
For example, in the following documentation page, you can see that `Type` column header is misaligned with its column cells.
https://taiga-ui.dev/services/scroll-service/API

### Angular version

14.2

### Taiga UI version

3

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by jrstrayhorn**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [x] Documentation content changes

## What is the current behavior?

scrollservice-before

Closes #2568  

## What is the new behavior?

scrollservice-after

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]

**Comment by jrstrayhorn** [comment]
@waterplea - fixed!

**Comment by splincode** [comment]
not good 

image

**Comment by jrstrayhorn** [comment]
ah.. I see... the value content isn't 100% width on mobile.... I'll take a look at that.

**Comment by jrstrayhorn** [comment]
@waterplea / @splincode - Mobile should be good now...
input-api-mobile-table-still-working

New Table Behavior still working...
scrollservice-after-still-working

**Pull request merged**
