### PR TITLE
test(kit): remove fdescribe from Action test

### PR DESCRIPTION
**Pull request by alvaromartmart**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

A `fdescribe` statement was left by mistake in the `Action` component spec and merged together with #2789... my bad, I was the author of that PR 😅  🤦‍♂️ 🤦‍♂️  

## What is the new behavior?

`fdescribe` changed to `describe`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by alvaromartmart** [comment]
BTW I think it would be good to add an `eslint` rule to forbid focused tests (`fdescribe` / `fit`), have you considered it?

**Review by splincode — APPROVED** [review]

**Review by nsbarsukov — APPROVED** [review]

**Review by nsbarsukov — COMMENTED** [review]
Could you also fix this test, please ?

```
Chrome Headless 106.0.5249.91 (Linux x86_64) Filter content items passed correctly if items is an array of objects with toString FAILED
	Error: Expected 'Focused Zone  10' to be 'Focused Zone 
	10'.
	    at <Jasmine>
	    at UserContext.<anonymous> (projects/kit/components/filter/test/filter.component.spec.ts:126:67)
	    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:1)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:1)
Chrome Headless 106.0.5249.91 (Linux x86_64) Filter content items passed correctly if items is an array of objects with toString FAILED
	Error: Expected 'Focused Zone  10' to be 'Focused Zone 
	10'.
	    at <Jasmine>
	    at UserContext.<anonymous> (projects/kit/components/filter/test/filter.component.spec.ts:126:67)
	    at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:1)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:1)
```

**Comment by nsbarsukov** [comment]
> BTW I think it would be good to add an `eslint` rule to forbid focused tests (`fdescribe` / `fit`), have you considered it?

Sounds good)

**Comment by waterplea** [comment]
Will be fixed here: https://github.com/Tinkoff/taiga-ui/pull/2840

**Pull request closed without merging**
