### PR TITLE
feat(core): extend secondary appearance variables set

### PR DESCRIPTION
**Pull request by anatoly-spb**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

The wrapper for the second appearance uses the --tui-link variable to specify a text color. It breaks customization for certain cases, for example: I want to change text color for secondary button, but I dont want to change --tui-link variable:
```
 <button tuiButton type="button" appearance="secondary">
        secondary
      </button>
```
as the result:
image

## What is the new behavior?

I propose to extend variable set for secondary appearance with current defaults and use them in the secondary.less:
```
    // extend secondary appearance properties:
    --tui-secondary-text: var(--tui-link);
    --tui-secondary-text-hover: var(--tui-link-hover);
    // for night:
    --tui-secondary-night: var(--tui-clear-inverse);
    --tui-secondary-hover-night: var(--tui-clear-inverse-hover);
    --tui-secondary-active-night: var(--tui-clear-inverse-active);
    --tui-secondary-text-night: var(--tui-text-01-night);
    --tui-secondary-text-hover-night: var(--tui-text-01-night);
    // for light:
    --tui-secondary-light: var(--tui-clear);
    --tui-secondary-hover-light: var(--tui-clear-hover);
    --tui-secondary-active-light: var(--tui-clear-active);
    --tui-secondary-text-light: var(--tui-text-01);
    --tui-secondary-text-hover-light: var(--tui-text-01);
```
It will allow to change secondary text and more without global share variables changes such as --tui-link and etc.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by KhaledGabr** [comment]
Thanks! The funny thing is I made an issue about that specific issue just yesterday. https://github.com/Tinkoff/taiga-ui/issues/3586

**Comment by waterplea** [comment]
I'm skeptical about introducing a lot of new vars. I would rather remove hover effect from text and drop secondary-text-hover variable. Also we never have "light" modifications for variables and overall tuiMode="onLight" is in a weird spot - it was introduced by our design team a looong time ago but I'm not sure if it's actually used. Let's not introduce variables for it and just code it in place this way?

**Comment by splincode** [comment]
@anatoly-spb any updates?

**Comment by waterplea** [comment]
@anatoly-spb I'm sorry, I'll have to close this PR. Just yesterday, our design team revealed plans to completely overhaul semantic names for CSS variables and introduce a whole new model to align with mobile development team. For easier transition, I'd like to keep it unchanged for now.

**Pull request closed without merging**
