### PR TITLE
feat(core): svg source interceptor should accept svg global options

### PR DESCRIPTION
**Pull request by splincode**
## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

image

## What is the new behavior?

image

### CODE REVIEW

**Comment by splincode** [comment]
@nsbarsukov @vladimirpotekhin hello, please review me

**Comment by splincode** [comment]
@vladimirpotekhin hello, please review me))

**Review by vladimirpotekhin — APPROVED** [review]
check proprietary please, just in case

**Comment by splincode** [comment]
Yes, I will check)

**Pull request merged**
