### PR TITLE
[DRAFT] ci: add playwright

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [x] Build or CI related changes
- [ ] Documentation content changes

### CODE REVIEW

**Comment by splincode** [comment]
@nsbarsukov I see that the screenshots are not attached by argus bot

image

**Comment by zarghamkhandev** [comment]
what value does playwright brings ? I thought we are having cypress for e2e tests.

**Comment by splincode** [comment]
@zarghamkhandev before on cypress

13min and 50min
image

after 

4min and 12min
image
image

**Comment by splincode** [comment]
It will be possible to return after e2e bot is fixed

**Pull request closed without merging**
