### PR TITLE
Update destroy.service.ts

### PR DESCRIPTION
**Pull request by evoytenkoapps**
Может лучше здесь ReplaySubject вместо обычного Subject?
Вот лис рекомендует использоваться его https://medium.com/ngx/why-do-you-need-unsubscribe-ee0c62b5d21f

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring
-   [ ] Code style update
-   [ ] Build or CI related changes
-   [ ] Documentation content changes

## What is the current behavior?

Closes # 

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [ ] No

### CODE REVIEW

**Review by waterplea — CHANGES_REQUESTED** [review]
Please add
```ts
constructor() {
  super(1);
}
```
otherwise the build fails since it's a decorated class and it tries to look for constructor param in the DI :)

**Comment by splincode** [comment]
@evoytenkoapps any updates?

**Comment by spierala** [comment]
Just curious... why the refactor from `Subject ` to `ReplaySubject(1)`?

I tried to find the answer [here](https://medium.com/angular-in-depth/why-you-have-to-unsubscribe-from-observable-92502d5639d0), but I am still not sure.

**Comment by waterplea** [comment]
> Just curious... why the refactor from `Subject ` to `ReplaySubject(1)`?
> 
> I tried to find the answer [here](https://medium.com/angular-in-depth/why-you-have-to-unsubscribe-from-observable-92502d5639d0), but I am still not sure.

It's an insurance from mostly theoretical case. If something subscribes to a stream after directive was already destroyed — it would immediately unsubscribe. Consider this case — you listen to `animationend` event to subscribe to something. If directive is destroyed, `ngOnDestroy` is called, then element is getting removed from DOM, if animation was still playing — callback gets called after `ngOnDestroy` and a subscription would not get terminated with plain `Subject` as destroy service.

**Pull request closed without merging**
