### PR TITLE
fix(i18n): fix vietnamese

### PR DESCRIPTION
**Pull request by annguyen-it**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [x] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes # 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Comment by waterplea** [comment]
@annguyen-it thank you for this contribution. Please run `prettier` on `scripts/shared/run-standard-version.ts`.

**Comment by annguyen-it** [comment]
> @annguyen-it thank you for this contribution. Please run `prettier` on `scripts/shared/run-standard-version.ts`.

I have run and nothing changes.

**Comment by splincode** [comment]
image

**Comment by annguyen-it** [comment]
Sorry, I had a mistake 😃

**Review by nsbarsukov — APPROVED** [review]

**Review by MarsiBarsi — APPROVED** [review]

**Pull request merged**
