### PR TITLE
fix(addon-editor): change width for the opacity block

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

image

image

## What is the new behavior?

image

image

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by waterplea — CHANGES_REQUESTED** [review]
This way postfix would overlay the icons. It is correct now, you should fix the example instead, make it wider and color input narrower.

**Review by waterplea — APPROVED** [review]

**Comment by vladimirpotekhin** [comment]
what about screenshot? left and right padding in the palette not the same now

**Comment by splincode** [comment]
@vladimirpotekhin fixed after rebase

**Comment by vladimirpotekhin** [comment]
> https://taiga-ui--pr1162-splincode-fix-value-vkuaemzx.web.app

the screenshot is gone, but it still seems like the padding is wrong https://taiga-ui--pr1162-splincode-fix-value-vkuaemzx.web.app/components/editor-new

**Review by vladimirpotekhin — APPROVED** [review]

**Pull request merged**
