### PR TITLE
fix(cdk): correct detect that is safari

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

### CODE REVIEW

**Review by waterplea — APPROVED** [review]
Tests seem pointless.

**Comment by splincode** [comment]
needed for Test-driven development (TDD) as mocks

**Comment by waterplea** [comment]
> needed for Test-driven development (TDD) as mocks

But they literally don't test anything.

**Comment by splincode** [comment]
why?

image

I expect `false` here

**Comment by splincode** [comment]
and `true` here

image

**Pull request merged**
