### PR TITLE
feat(kit): add month input options DI token

### PR DESCRIPTION
**Pull request by alvaromartmart**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

#2785 solved #2756 and also made customizable the `min` and `max` input defaults through the options DI token, as suggested by @waterplea during code review.

However, I just discovered there were a couple of additional components that should probably implement the same changes: the `input-month` and `input-month-range` components.

## What is the new behavior?

This PR adds a `TUI_INPUT_MONTH_OPTIONS` DI token that allows customization of calendar icon, min and max values, following the same approach done in #2785.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by waterplea** [comment]
Looks like we can reuse the same token here, `TuiDay` extends `TuiMonth`.

**Comment by alvaromartmart** [comment]
> Looks like we can reuse the same token here, `TuiDay` extends `TuiMonth`.

Thanks, done!

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]
That's a weird test fail. @splincode can you take a look?

**Comment by waterplea** [comment]
Oh, I see. Let's fix it here:
https://github.com/Tinkoff/taiga-ui/pull/2839
@alvaromartmart I'm not sure where it came from, but you can probably just change the expected outcome. Just need to make sure it looks as it supposed to. Perhaps some changes removed a whitespace that is not rendered anyway.

**Comment by waterplea** [comment]
@alvaromartmart yes, please go ahead and change expected output.

**Pull request merged**
