### PR TITLE
fix(core): fixed styles for form header

### PR DESCRIPTION
**Pull request by gyxman**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?
Additional classes for form header do not work 

Closes # 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]

**Comment by splincode** [comment]
@waterplea what do you think about?

image

Do we need to wrap it in ignore?

**Comment by waterplea** [comment]
> @waterplea what do you think about?
> 
> image
> 
> Do we need to wrap it in ignore?

Style lint is the least thing I care about, so either solution is fine with me 😄

**Comment by splincode** [comment]
@gyxman please, update your pr with `stylelint ignore`

**Comment by gyxman** [comment]
Done. But maybe think about fix the order of the rules

**Comment by gyxman** [comment]
> @gyxman please, update your pr with `stylelint ignore`

Done. But maybe think about fix the order of the rules

**Comment by splincode** [comment]
@gyxman Could you please update rules in https://github.com/Tinkoff/linters?

**Pull request merged**
