### PR TITLE
feat(testing): accordion harness test

### PR DESCRIPTION
**Pull request by zarghamkhandev**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

Partially implements https://github.com/Tinkoff/taiga-ui/issues/476

## What is the new behavior?
Introduces ComponentHarness for card component.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Comment by splincode** [comment]
@zarghamkhandev squash all commits please

**Comment by zarghamkhandev** [comment]
@splincode  done ✅

**Comment by zarghamkhandev** [comment]
@splincode  can we get this merged.

**Comment by splincode** [comment]
@waterplea

**Review by waterplea — APPROVED** [review]

**Pull request merged**
