### PR TITLE
feat(core): `TUI_VIEWPORT` add new token

### LINKED ISSUE #3540: 🐞 - Data list items truncated when window scale isn't equal 100%
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

Zoom in browser window using mousewheel  + ctrl/touchpad, then open dropdown and there won't be all items present in the list, and also it's impossible to scroll to them or find the missing options by search. 
After zooming out to normal scale everything works as usual.

UIKIT-6263

### Angular version

12.2.16

### Taiga UI version

2.58.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by waterplea**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3540

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Comment by splincode** [comment]
is this the expected behavior?

image

image

**Comment by waterplea** [comment]
> is this the expected behavior?
> 
> image
> 
> image

Kind of. There's no better way for this dropdown to show, editor is too short. As for the top image, do you know why there's border instead of margin? Margin seems to behave the same, at a glance, and dropdown switches to down at the correct moment.

**Comment by splincode** [comment]
@waterplea Now I understand what happens at the time of the screenshot on cypress and why screenshots can sometimes behave this way
https://user-images.githubusercontent.com/12021443/217459813-da4824c2-be1f-463e-a74f-3cc9bc2f11c1.mov

**Comment by waterplea** [comment]
> @waterplea Now I understand what happens at the time of the screenshot on cypress and why screenshots can sometimes behave this way
> 
> 
> https://user-images.githubusercontent.com/12021443/217460058-5f8c29d1-7ecd-49c0-9837-086b437b48b0.mov
> 
> 
> 

But aren't we disabling animations for Cypress?

**Review by nsbarsukov — APPROVED** [review]

**Comment by splincode** [comment]
`But aren't we disabling animations for Cypress?` you are right

https://user-images.githubusercontent.com/12021443/217564739-df25845c-3783-49bf-b24f-31afdce23cd1.mov


https://user-images.githubusercontent.com/12021443/217564827-d2a00b1c-ae9c-4cf6-aacb-73697321cc83.mov

**Comment by waterplea** [comment]
> `But aren't we disabling animations for Cypress?` you are right

Maybe we should also set hide delay to 0.

**Comment by splincode** [comment]
@waterplea `Maybe we should also set hide delay to 0.`

https://github.com/Tinkoff/taiga-ui/pull/3643

**Pull request merged**
